from language import Environment, ParseTree, EvalResult
from typing import Callable

def pprint_result(result: EvalResult) -> None: ...
def execute(parse_tree: ParseTree, environment: Environment) -> EvalResult: ...
