from language import Environment as Environment, ParseTree, Token
from typing import Protocol

type EvalResult = Token | list['EvalResult']
class _ApplyFunc(Protocol):
    def __call__(self, args: list[ParseTree], env: Environment) -> EvalResult: ...

def pprint_result(result: EvalResult) -> None: ...
def execute(parse_tree: ParseTree, environment: Environment) -> Token: ...
