from typing import Any, Callable, Protocol
from language import ParseTree, Token, Environment

type EvalResult = Token | list['EvalResult']

class _ApplyFunc(Protocol):
    def __call__(self, args: list[ParseTree], env: Environment) -> EvalResult: ...

def pprint_result(result: EvalResult) -> None: ...
def _eval(node: ParseTree, env: Environment) -> EvalResult: ...
def _apply(func: _ApplyFunc, args: list[ParseTree], env: Environment) -> EvalResult: ...
def _eval_list(nodes: list[ParseTree], env: Environment) -> list[EvalResult]: ...
def _bind_special_form(name: str, handler: Callable[[list[ParseTree], Environment], EvalResult]) -> None: ...
def _bind_builtin(name: str, handler: _ApplyFunc) -> None: ...
def _make_closure(params: list[str], body: list[ParseTree], env: Environment) -> _ApplyFunc: ...
